[workspace]
members = [
<<<<<<< HEAD
	"bin/node-template",
	"bin/node-template/runtime",
	"bin/node/cli",
	"bin/node/executor",
	"bin/node/primitives",
	"bin/node/rpc-client",
	"bin/node/rpc",
	"bin/node/runtime",
	"bin/node/testing",
	"bin/subkey",
	"client",
	"client/api",
	"client/authority-discovery",
	"client/basic-authorship",
	"client/block-builder",
	"client/chain-spec",
	"client/chain-spec/derive",
	"client/cli",
	"client/consensus/aura",
	"client/consensus/babe",
	"client/consensus/pow",
	"client/consensus/slots",
	"client/consensus/uncles",
	"client/db",
	"client/executor",
	"client/executor/runtime-test",
	"client/finality-grandpa",
	"client/header-metadata",
	"client/keystore",
	"client/network",
	"client/offchain",
	"client/rpc-servers",
	"client/rpc",
	"client/rpc/api",
	"client/service",
	"client/service/test",
	"client/state-db",
	"client/telemetry",
	"client/transaction-pool",
	"client/transaction-pool/graph",
	"client/utils/wasm-builder-runner",
	"paint/assets",
	"paint/aura",
	"paint/authority-discovery",
	"paint/authorship",
	"paint/babe",
	"paint/balances",
	"paint/collective",
	"paint/contracts",
	"paint/contracts/rpc",
	"paint/contracts/rpc/runtime-api",
	"paint/democracy",
	"paint/elections-phragmen",
	"paint/elections",
	"paint/evm",
	"paint/example",
	"paint/executive",
	"paint/finality-tracker",
	"paint/generic-asset",
	"paint/grandpa",
	"paint/im-online",
	"paint/indices",
	"paint/membership",
	"paint/metadata",
	"paint/nicks",
	"paint/offences",
	"paint/randomness-collective-flip",
	"paint/scored-pool",
	"paint/session",
	"paint/staking",
	"paint/staking/reward-curve",
	"paint/sudo",
	"paint/support",
	"paint/support/procedural",
	"paint/support/procedural/tools",
	"paint/support/procedural/tools/derive",
	"paint/support/rpc",
	"paint/support/test",
	"paint/system",
	"paint/system/rpc",
	"paint/system/rpc/runtime-api",
	"paint/timestamp",
	"paint/transaction-payment",
	"paint/transaction-payment/rpc",
	"paint/transaction-payment/rpc/runtime-api",
	"paint/treasury",
	"paint/utility",
	"primitives/application-crypto",
	"primitives/authority-discovery",
	"primitives/block-builder/runtime-api",
	"primitives/consensus/aura",
	"primitives/consensus/babe",
	"primitives/consensus/common",
	"primitives/consensus/pow",
	"primitives/core",
	"primitives/core/debug-derive",
	"primitives/core/storage",
	"primitives/externalities",
	"primitives/finality-grandpa",
	"primitives/inherents",
	"primitives/keyring",
	"primitives/offchain",
	"primitives/panic-handler",
	"primitives/peerset",
	"primitives/phragmen",
	"primitives/rpc",
	"primitives/runtime-interface",
	"primitives/runtime-interface/proc-macro",
	"primitives/runtime-interface/test-wasm",
	"primitives/serializer",
	"primitives/session",
	"primitives/sr-api",
	"primitives/sr-api/proc-macro",
	"primitives/sr-api/test",
	"primitives/sr-arithmetic",
	"primitives/sr-io",
	"primitives/sr-primitives",
	"primitives/sr-sandbox",
	"primitives/sr-staking-primitives",
	"primitives/sr-std",
	"primitives/sr-version",
	"primitives/state-machine",
	"primitives/transaction-pool/runtime-api",
	"primitives/trie",
	"primitives/wasm-interface",
	"test/utils/chain-spec-builder",
	"test/utils/client",
	"test/utils/primitives",
	"test/utils/runtime",
	"test/utils/runtime/client",
	"test/utils/transaction-factory",
	"utils/build-script-utils",
	"utils/fork-tree",
	"utils/wasm-builder",
=======
	"core/prometheus",
	"core/authority-discovery",
	"core/application-crypto",
	"core/chain-spec",
	"core/chain-spec/derive",
	"core/cli",
	"core/client",
	"core/client/db",
	"core/client/header-metadata",
	"core/consensus/aura",
	"core/consensus/babe",
	"core/consensus/common",
	"core/consensus/rhd",
	"core/consensus/slots",
	"core/consensus/uncles",
	"core/consensus/pow",
	"core/block-builder",
	"core/block-builder/runtime-api",
	"core/executor",
	"core/executor/runtime-test",
	"core/externalities",
	"core/finality-grandpa",
	"core/finality-grandpa/primitives",
	"core/inherents",
	"core/keyring",
	"core/keystore",
	"core/network",
	"core/panic-handler",
	"core/primitives",
	"core/rpc",
	"core/rpc/primitives",
	"core/rpc-servers",
	"core/runtime-interface",
	"core/runtime-interface/proc-macro",
	"core/runtime-interface/test-wasm",
	"core/serializer",
	"core/service",
	"core/service/test",
	"core/session",
	"core/sr-api",
	"core/sr-api/proc-macro",
	"core/sr-api/test",
	"core/sr-arithmetic",
	"core/sr-io",
	"core/sr-primitives",
	"core/sr-staking-primitives",
	"core/sr-sandbox",
	"core/sr-std",
	"core/sr-version",
	"core/state-machine",
	"core/telemetry",
	"core/test-client",
	"core/test-runtime",
	"core/test-runtime/client",
	"core/transaction-pool",
	"core/transaction-pool/graph",
	"core/transaction-pool/runtime-api",
	"core/trie",
	"core/utils/fork-tree",
	"core/utils/wasm-builder",
	"core/utils/wasm-builder-runner",
	"core/wasm-interface",
	"srml/support",
	"srml/support/rpc",
	"srml/support/procedural",
	"srml/support/procedural/tools",
	"srml/support/procedural/tools/derive",
	"srml/support/test",
	"srml/authorship",
	"srml/assets",
	"srml/aura",
	"srml/balances",
	"srml/contracts",
	"srml/contracts/rpc",
	"srml/collective",
	"srml/democracy",
	"srml/elections",
	"srml/elections-phragmen",
	"srml/example",
	"srml/executive",
	"srml/finality-tracker",
	"srml/generic-asset",
	"srml/grandpa",
	"srml/im-online",
	"srml/authority-discovery",
	"srml/indices",
	"srml/membership",
	"srml/metadata",
	"srml/nicks",
	"srml/offences",
	"srml/randomness-collective-flip",
	"srml/scored-pool",
	"srml/session",
	"srml/staking",
	"srml/staking/reward-curve",
	"srml/sudo",
	"srml/system",
	"srml/system/rpc",
	"srml/timestamp",
	"srml/treasury",
	"srml/transaction-payment",
	"srml/transaction-payment/rpc",
	"srml/utility",
	"srml/evm",
	"node/cli",
	"node/executor",
	"node/primitives",
	"node/rpc",
	"node/rpc-client",
	"node/runtime",
	"node/testing",
	"node-template",
	"subkey",
	"test-utils/chain-spec-builder",
>>>>>>> b9f9ac5a39c114629ddadb9fa20ca8ba7ab7f56d
]

[profile.release]
# Substrate runtime requires unwinding.
panic = "unwind"
